### PR TITLE
Implementation for Hysen and Floureon thermostats

### PR DESCRIPTION
**Pull request by alpapad**
Would you be interested in something like this?

It is wip, and needs a definition for the hysen device (basically a description and a type)

### CODE REVIEW

**Comment by a1aw** [comment]
Hi, sorry for a late reply. It would be a good idea to add these device into the library. 

However, your indentation seems to be incorrect. We use spaced indentation to ensure the file is correctly indented and can read in any systems. You can take a look of this to see how to change your IDE indentation format: https://github.com/mob41/broadlink-java-api/blob/master/CONTRIBUTING.md

Also BLDevice.java except the devType stuff supposed not to be changed.

**Comment by alpapad** [comment]
I am out, on vacation.

I will update and push a new PR.

Thanks.

**Comment by alpapad** [comment]
I think I must have a different setting for new lines, that is why BLDevice.java show so many diffs.. 

I will need some time to fix this. In the mean time, indention used for the rest of the files is 4spaces + nl at end of file.

**Comment by alpapad** [comment]
Hi, it should be ok now.

**Comment by a1aw** [comment]
Cause I don't have any of these devices, I cannot check if it is working. Do you have these devices and tested working?

**Comment by alpapad** [comment]
I have the Floureon one, and it is working fine. 
I copied the code from the python lib (impl for Hysen), and tested with my device. My device has a different code than the Hysen one and that is the only  difference as far as I can tell. Seems there is a family of such devices (I think people have reported the python code working on other models as well) that either share the same code as the Hysen one, or have a different code, but with the exact same functionality..

Later on I am planning on having unit tests for the device, to check each function.  All functions are supported. The only "grey" area in this implementation is that the devices send response codes per command, but these are not really checked (would love to know what they send back). Same applies to the python lib...

**Comment by a1aw** [comment]
Seems the code requires tidying afterwards. Your ```****Command.java``` that extends ```CmdPayload``` would be better to be placed in ```com/github/mob41/blapi/pkt/cmd/hysen``` instead.

**Pull request merged**
